# Generated by Django 4.0.2 on 2022-04-18 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, null=True)),
                ('gender', models.CharField(max_length=30, null=True)),
                ('mobile_no', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30)),
                ('is_admin', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='EnquiryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('car_model', models.CharField(max_length=30)),
                ('manufacture_year', models.CharField(max_length=20)),
                ('parts_name', models.CharField(max_length=30)),
                ('parts_image', models.CharField(max_length=300)),
                ('status', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customerinfo')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('mobile_no', models.CharField(max_length=30)),
                ('company_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='QuotationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('image', models.CharField(max_length=300)),
                ('enquiry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.enquiryinfo')),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.supplierinfo')),
            ],
        ),
    ]
