# Generated by Django 4.0.2 on 2022-04-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customerinfo_email_alter_supplierinfo_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
