# Generated by Django 4.0.2 on 2022-04-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customerinfo_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinfo',
            name='is_admin',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
