# Generated by Django 4.0.2 on 2022-04-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_customerinfo_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinfo',
            name='password',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
