# Generated by Django 4.0.2 on 2022-04-19 06:26

import customer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_enquiryinfo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiryinfo',
            name='parts_image',
            field=models.ImageField(blank=True, null=True, upload_to=customer.models.upload_path),
        ),
        migrations.AlterField(
            model_name='quotationinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=customer.models.upload_path),
        ),
    ]
